import type { DemoDatabase } from "@/types/domain";

const now = new Date().toISOString();

export const demoSeed: DemoDatabase = {
  companies: [
    { id: "company-acme", name: "Acme Varejo", slug: "acme-varejo", status: "ACTIVE" },
    { id: "company-beta", name: "Beta Distribuidora", slug: "beta-distribuidora", status: "ACTIVE" },
  ],
  users: [
    {
      id: "user-ana",
      name: "Ana Gestora",
      email: "ana@estoque.local",
      password: "123456",
      status: "ACTIVE",
    },
    {
      id: "user-bruno",
      name: "Bruno Operador",
      email: "bruno@estoque.local",
      password: "123456",
      status: "ACTIVE",
    },
  ],
  userCompanies: [
    {
      id: "uc-1",
      userId: "user-ana",
      companyId: "company-acme",
      role: "ADMIN",
      isActive: true,
    },
    {
      id: "uc-3",
      userId: "user-bruno",
      companyId: "company-beta",
      role: "STORAGE_CLERK",
      isActive: true,
    },
  ],
  categories: [
    {
      id: "category-acme-1",
      companyId: "company-acme",
      name: "Insumos",
      description: "Materiais de consumo recorrente.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "category-beta-1",
      companyId: "company-beta",
      name: "Revenda",
      description: "Produtos preparados para revenda.",
      createdAt: now,
      updatedAt: now,
    },
  ],
  brands: [
    {
      id: "brand-acme-1",
      companyId: "company-acme",
      name: "Nestle",
      description: undefined,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "brand-acme-2",
      companyId: "company-acme",
      name: "Coca-Cola",
      description: undefined,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "brand-beta-1",
      companyId: "company-beta",
      name: "3M",
      description: undefined,
      createdAt: now,
      updatedAt: now,
    },
  ],
  locations: [
    {
      id: "loc-acme-1",
      companyId: "company-acme",
      parentId: undefined,
      name: "Galpao A",
      level: 0,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "loc-acme-2",
      companyId: "company-acme",
      parentId: "loc-acme-1",
      name: "Rua 01",
      level: 1,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "loc-acme-3",
      companyId: "company-acme",
      parentId: "loc-acme-2",
      name: "Prateleira 02",
      level: 2,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "loc-acme-4",
      companyId: "company-acme",
      parentId: "loc-acme-3",
      name: "Nivel 03",
      level: 3,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "loc-beta-1",
      companyId: "company-beta",
      parentId: undefined,
      name: "Deposito Central",
      level: 0,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "loc-beta-2",
      companyId: "company-beta",
      parentId: "loc-beta-1",
      name: "Corredor B",
      level: 1,
      sortOrder: 1,
      createdAt: now,
      updatedAt: now,
    },
  ],
  suppliers: [
    {
      id: "supplier-acme-1",
      companyId: "company-acme",
      name: "Distribuidora de Papeis Ltda",
      cnpj: "11222333000181",
      contact: "Carlos",
      phone: "(11) 99999-0001",
      email: "carlos@distpapeis.com.br",
      address: "Rua dos Papéis, 100, SP",
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "supplier-acme-2",
      companyId: "company-acme",
      name: "Embalagens Premium S.A.",
      cnpj: "44555666000199",
      contact: "Marina",
      phone: "(11) 98888-0002",
      email: "marina@embpremium.com",
      address: "Av das Embalagens, 200, SP",
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "supplier-beta-1",
      companyId: "company-beta",
      name: "Caixas e Cia Ltda",
      cnpj: "77888999000111",
      contact: "Roberto",
      phone: "(21) 97777-0003",
      email: "roberto@caixasecia.com",
      address: "Rua das Caixas, 50, RJ",
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
  ],
  inventoryCounts: [],
  inventoryCountItems: [],
  products: [
    {
      id: "product-acme-1",
      companyId: "company-acme",
      categoryId: "category-acme-1",
      name: "Papel A4",
      sku: "PAP-A4-001",
      costPrice: 22.5,
      unit: "BOX",
      minimumStock: 5,
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-acme-2",
      companyId: "company-acme",
      categoryId: "category-acme-1",
      name: "Toner HP 85A",
      sku: "TON-HP-85A",
      costPrice: 189.9,
      unit: "UNIT",
      minimumStock: 3,
      expiryDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-acme-3",
      companyId: "company-acme",
      categoryId: "category-acme-1",
      name: "Caneta Azul",
      sku: "CAN-AZ-001",
      costPrice: 1.5,
      unit: "UNIT",
      minimumStock: 50,
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-acme-4",
      companyId: "company-acme",
      categoryId: "category-acme-1",
      name: "Lapis Preto",
      sku: "LAP-PR-001",
      costPrice: 0.8,
      unit: "UNIT",
      minimumStock: 30,
      status: "ACTIVE",
      createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "product-beta-1",
      companyId: "company-beta",
      categoryId: "category-beta-1",
      name: "Caixa Organizadora",
      sku: "CX-ORG-001",
      costPrice: 15.75,
      unit: "UNIT",
      minimumStock: 10,
      status: "ACTIVE",
      createdAt: now,
      updatedAt: now,
    },
  ],
  inventoryBalances: [
    {
      id: "balance-acme-1",
      companyId: "company-acme",
      productId: "product-acme-1",
      currentQuantity: 12,
      updatedAt: now,
    },
    {
      id: "balance-acme-2",
      companyId: "company-acme",
      productId: "product-acme-2",
      currentQuantity: 2,
      updatedAt: now,
    },
    {
      id: "balance-acme-3",
      companyId: "company-acme",
      productId: "product-acme-3",
      currentQuantity: 0,
      updatedAt: now,
    },
    {
      id: "balance-acme-4",
      companyId: "company-acme",
      productId: "product-acme-4",
      currentQuantity: 10,
      updatedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "balance-beta-1",
      companyId: "company-beta",
      productId: "product-beta-1",
      currentQuantity: 24,
      updatedAt: now,
    },
  ],
  inventoryMovements: [
    {
      id: "move-acme-1",
      companyId: "company-acme",
      productId: "product-acme-1",
      performedByUserId: "user-ana",
      type: "ENTRY",
      quantity: 12,
      previousQuantity: 0,
      resultingQuantity: 12,
      note: "Carga inicial para validacao.",
      createdAt: now,
    },
    {
      id: "move-beta-1",
      companyId: "company-beta",
      productId: "product-beta-1",
      performedByUserId: "user-ana",
      type: "ENTRY",
      quantity: 24,
      previousQuantity: 0,
      resultingQuantity: 24,
      note: "Carga inicial para validacao.",
      createdAt: now,
    },
  ],
};
